default:
  before_script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY

clientes:
  stage: build
  script:
    - |
      docker build -t teste-clientes -f microservice-clientes/devops/Dockerfile-CI .
      docker run --name teste-clientes-build -v /var/run/docker.sock:/var/run/docker.sock teste-clientes
      docker cp teste-clientes-build:/app/sources/target/microservice-clientes-0.0.1-SNAPSHOT.jar microservice-clientes/app.jar
      cd microservice-clientes
      docker build -t diegoalexandrooliveira/biblioteca-clientes:latest -f devops/Dockerfile-CD .
      docker rm -f teste-clientes-build
      docker rmi teste-clientes
      docker push diegoalexandrooliveira/biblioteca-clientes:latest

livros:
  stage: build
  script:
    - |
      docker build -t teste-livros -f microservice-livros/devops/Dockerfile-CI .
      docker run --name teste-livros-build -v /var/run/docker.sock:/var/run/docker.sock teste-livros
      docker cp teste-livros-build:/app/sources/target/microservice-livros-0.0.1-SNAPSHOT.jar microservice-livros/app.jar
      cd microservice-livros
      docker build -t diegoalexandrooliveira/biblioteca-livros:latest -f devops/Dockerfile-CD .
      docker rm -f teste-livros-build
      docker rmi teste-livros
      docker push diegoalexandrooliveira/biblioteca-livros:latest

emprestimos:
  stage: build
  script:
    - |
      docker build -t teste-emprestimos -f microservice-emprestimos/devops/Dockerfile-CI .
      docker run --name teste-emprestimos-build -v /var/run/docker.sock:/var/run/docker.sock teste-emprestimos
      docker cp teste-emprestimos-build:/app/sources/target/microservice-emprestimos-0.0.1-SNAPSHOT.jar microservice-emprestimos/app.jar
      cd microservice-emprestimos
      docker build -t diegoalexandrooliveira/biblioteca-emprestimos:latest -f devops/Dockerfile-CD .
      docker rm -f teste-emprestimos-build
      docker rmi teste-emprestimos
      docker push diegoalexandrooliveira/biblioteca-emprestimos:latest