spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/biblioteca-clientes
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  servlet:
    context-path: '/api/clientes-ms/'
keycloak:
  realm: 'biblioteca'
  resource: 'clientes'
  auth-server-url: http://localhost:8000/auth
  bearer-only: true
  use-resource-role-mappings: true