spring:
  data:
    mongodb:
      database: emprestimos
      username: root
      password: root
      authentication-database: admin
  kafka:
    properties:
      schema.registry.url: http://localhost:8040
    consumer:
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
server:
  port: 8003
  servlet:
    context-path: '/api/service/'
keycloak:
  realm: 'biblioteca'
  resource: 'emprestimos'
  auth-server-url: http://localhost:8000/auth
  bearer-only: true
  use-resource-role-mappings: true
kafka:
  consumer:
    topic-clientes: novos-clientes
    topic-clientes-group-id: 1
    topic-livros: novos-livros
    topic-livros-group-id: 1