spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: emprestimos
      username: root
      password: root
      authentication-database: ${MONGO_AUTH_DB:admin}
  kafka:
    bootstrap-servers: ${KAFKA_URL:172.17.0.1:29092}
    properties:
      schema.registry.url: ${KAFKA_REGISTRY_URL:http://localhost:8040}
      specific.avro.reader: true
    consumer:
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
server:
  port: 8003
  servlet:
    context-path: '/api/service/'
keycloak:
  realm: 'biblioteca'
  resource: 'emprestimos'
  auth-server-url: http://localhost:8000/auth
  bearer-only: true
  use-resource-role-mappings: true
kafka:
  consumer:
    clientes:
      topic: novos-clientes
      group-id: 1
    livros:
      novos:
        topic: livros-novos
        group-id: 1
      adiciona-copia:
        topic: livros-adiciona-copia
        group-id: 1
        dlq: livros-adiciona-copia-dlq
      remove-copia:
        topic: livros-remove-copia
        group-id: 1
        dlq: livros-remove-copia-dlq
