FROM ghcr.io/graalvm/graalvm-ce:java11-21.0.0.2

COPY ./app.jar /app/app.jar

WORKDIR /app/

EXPOSE 8080

ENTRYPOINT exec java \
            -Dspring.datasource.username=$DB_USERNAME \
            -Dspring.datasource.password=$DB_PASSWORD \
            -Dspring.datasource.url=$DB_URL \
            -Dspring.kafka.bootstrap-servers=$KAFKA_URL \
            -Dkeycloak.auth-server-url=$KEYCLOAK_URL \
            -Demprestimo.service-url=$EMPRESTIMO_URL \
            -Demprestimo.oauth2.username=$EMPRESTIMO_USERNAME \
            -Demprestimo.oauth2.password=$EMPRESTIMO_PASSWORD \
            -Demprestimo.oauth2.access-token-uri=$EMPRESTIMO_IDENTITY_PROVIDER_URI \
            -Demprestimo.oauth2.client-id=$EMPRESTIMO_CLIENT_ID \
            -jar app.jar