apiVersion: v1
kind: List
items:
  # Zookeeper
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zookeeper
      labels:
        app: zookeeper
    spec:
      selector:
        matchLabels:
          app: zookeeper
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: zookeeper
        spec:
          containers:
            - name: zookeeper
              image: 'confluentinc/cp-zookeeper:6.1.0'
              imagePullPolicy: Always
              ports:
                - containerPort: 2181
                  protocol: TCP
              env:
                - name: ZOOKEEPER_CLIENT_PORT
                  value: '2181'
                - name: ZOOKEEPER_TICK_TIME
                  value: '2000'

  - apiVersion: v1
    kind: Service
    metadata:
      name: zookeeper-service
    spec:
      selector:
        app: zookeeper
      ports:
        - protocol: TCP
          port: 2181
          targetPort: 2181

  # Broker
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: broker
      labels:
        app: broker
    spec:
      selector:
        matchLabels:
          app: broker
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: broker
        spec:
          containers:
            - name: broker
              image: 'confluentinc/cp-kafka:6.1.0'
              imagePullPolicy: Always
              ports:
                - containerPort: 29092
                  protocol: TCP
              env:
                - name: KAFKA_BROKER_ID
                  value: '1'
                - name: KAFKA_ZOOKEEPER_CONNECT
                  value: 'zookeeper-service:2181'
                - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                  value: 'PLAINTEXT_SERVICE:PLAINTEXT,PLAINTEXT:PLAINTEXT'
                - name: KAFKA_ADVERTISED_LISTENERS
                  value: 'PLAINTEXT://localhost:9092,PLAINTEXT_SERVICE://broker-service:29092'
                - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                  value: '1'
                - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                  value: '1'
                - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                  value: '1'
                - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
                  value: '0'
                - name: KAFKA_JMX_PORT
                  value: '9101'
                - name: KAFKA_JMX_HOSTNAME
                  value: 'localhost'

  - apiVersion: v1
    kind: Service
    metadata:
      name: broker-service
    spec:
      selector:
        app: broker
      ports:
        - protocol: TCP
          name: porta-29092
          port: 29092
          targetPort: 29092
        - protocol: TCP
          name: porta-9092
          port: 9092
          targetPort: 9092

  # Registry
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: registry
      labels:
        app: registry
    spec:
      selector:
        matchLabels:
          app: registry
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: registry
        spec:
          containers:
            - name: registry
              image: 'confluentinc/cp-schema-registry:6.1.0'
              imagePullPolicy: Always
              ports:
                - containerPort: 8081
                  protocol: TCP
              env:
                - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
                  value: 'broker-service:29092'
                - name: SCHEMA_REGISTRY_LISTENERS
                  value: 'http://0.0.0.0:8081'
                - name: SCHEMA_REGISTRY_HOST_NAME
                  value: 'localhost'

  - apiVersion: v1
    kind: Service
    metadata:
      name: registry-service
    spec:
      selector:
        app: registry
      ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081

  # Kafdrop
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kafdrop
      labels:
        app: kafdrop
    spec:
      selector:
        matchLabels:
          app: kafdrop
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: kafdrop
        spec:
          containers:
            - name: kafdrop
              image: 'obsidiandynamics/kafdrop:latest'
              imagePullPolicy: Always
              ports:
                - containerPort: 9000
                  protocol: TCP
              env:
                - name: KAFKA_BROKERCONNECT
                  value: 'broker-service:29092'
                - name: JVM_OPTS
                  value: '-Xms32M -Xmx64M'
                - name: SERVER_SERVLET_CONTEXTPATH
                  value: '/'
                - name: CMD_ARGS
                  value: '--schemaregistry.connect=http://registry-service:8081'

  - apiVersion: v1
    kind: Service
    metadata:
      name: kafdrop-service
    spec:
      type: NodePort
      selector:
        app: kafdrop
      ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
