apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      selector:
        matchLabels:
          app: keycloak
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: keycloak
        spec:
          containers:
            - name: keycloak
              image: 'jboss/keycloak:12.0.4'
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: KEYCLOAK_USER
                  value: 'admin'
                - name: KEYCLOAK_PASSWORD
                  value: 'admin'
                - name: DB_VENDOR
                  value: 'postgres'
                - name: DB_ADDR
                  value: 'postgres-service'
                - name: DB_PORT
                  value: '5432'
                - name: DB_USER
                  value: 'postgres'
                - name: DB_PASSWORD
                  value: 'postgres'

  - apiVersion: v1
    kind: Service
    metadata:
      name: keycloak-service
    spec:
      type: NodePort
      selector:
        app: keycloak
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
