apiVersion: v1
kind: List
items:
  # MongoDB
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      selector:
        matchLabels:
          app: mongodb
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: mongodb
        spec:
          containers:
            - name: mongodb
              image: 'mongo:4.2.12-bionic'
              imagePullPolicy: Always
              ports:
                - containerPort: 27017
                  protocol: TCP
              env:
                - name: MONGO_INITDB_ROOT_USERNAME
                  value: 'root'
                - name: MONGO_INITDB_ROOT_PASSWORD
                  value: 'root'

  - apiVersion: v1
    kind: Service
    metadata:
      name: mongodb-service
    spec:
      selector:
        app: mongodb
      ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017

  # MongoDB Express
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mongodb-express
      labels:
        app: mongodb-express
    spec:
      selector:
        matchLabels:
          app: mongodb-express
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: mongodb-express
        spec:
          containers:
            - name: mongodb-express
              image: 'mongo-express'
              imagePullPolicy: Always
              ports:
                - containerPort: 8081
                  protocol: TCP
              env:
                - name: ME_CONFIG_MONGODB_SERVER
                  value: 'mongodb-service'
                - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                  value: 'root'
                - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                  value: 'root'

  - apiVersion: v1
    kind: Service
    metadata:
      name: mongodb-express-service
    spec:
      type: NodePort
      selector:
        app: mongodb-express
      ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081