apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      selector:
        matchLabels:
          app: postgres
      replicas: 1
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: postgres
        spec:
          containers:
            - name: postgres
              image: 'postgres:13-alpine'
              imagePullPolicy: Always
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRES_PASSWORD
                  value: 'postgres'

  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres-service
    spec:
      type: NodePort
      selector:
        app: postgres
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
