FROM ghcr.io/graalvm/graalvm-ce:java11-21.0.0.2

COPY ./app.jar /app/app.jar

WORKDIR /app/

EXPOSE 8080

ENTRYPOINT exec java \
            -Dspring.datasource.username=$DB_USERNAME \
            -Dspring.datasource.password=$DB_PASSWORD \
            -Dspring.datasource.url=$DB_URL \
            -Dkeycloak.auth-server-url=$KEYCLOAK_URL \
            -Dspring.kafka.bootstrap-servers=$KAFKA_URL \
            -jar app.jar