FROM openjdk:11-jre-slim

COPY ./app.jar /app/app.jar

WORKDIR /app/

EXPOSE 8080

ENTRYPOINT exec java \
            -Dspring.datasource.username=$DB_USERNAME \
            -Dspring.datasource.password=$DB_PASSWORD \
            -Dspring.datasource.url=$DB_URL \
            -Dkeycloak.auth-server-url=$KEYCLOAK_URL \
            -jar app.jar