FROM ghcr.io/graalvm/graalvm-ce:latest:java11-21.0.0.2

COPY ./app.jar /app/app.jar

WORKDIR /app/

EXPOSE 8080

ENTRYPOINT exec java \
            -Dspring.data.mongodb.host=$MONGO_HOST \
            -Dspring.data.mongodb.port=$MONGO_PORT \
            -Dspring.data.mongodb.database=$MONGO_DATABASE \
            -Dspring.data.mongodb.username=$MONGO_USERNAME \
            -Dspring.data.mongodb.password=$MONGO_PASSWORD \
            -Dkeycloak.auth-server-url=$KEYCLOAK_URL \
            -Dkafka.properties.schema.registry.url=$KAFKA_REGISTRY_URL \
            -Dspring.kafka.bootstrap-servers=$KAFKA_URL \
            -jar app.jar